# Path: production/argocd/apps/platform/2-cert-manager.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    # Wave 2: Instalação base de certificados, uma das primeiras dependências.
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: camunda-platform
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    # A versão v1.15+ é uma ótima escolha estável.
    targetRevision: v1.15.3
    helm:
      releaseName: cert-manager
      valuesObject:
        # Essencial para que o Helm instale as Definições de Recurso Customizado (CRDs).
        installCRDs: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
