# Path: production/argocd/apps/platform/2-secrets.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-manager
  namespace: argocd
  annotations:
    # Wave 2: Aplica os segredos após a infra base estar pronta.
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: camunda-platform
  source:
    repoURL: git@github.com:Unicoon-Protecao-Veicular/SGP.git # Substitua pelo seu repo
    path: production/k8s/secrets # Aponta para o diretório que contém os SealedSecrets
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    # O namespace é definido dentro de cada manifesto de SealedSecret.
    # 'default' é usado como placeholder.
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true