# production/argocd/apps/platform/5-external-secrets.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
  annotations:
    # Wave 5: Monitoramento pode ser instalado após a infraestrutura principal.
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: camunda-platform
  source:
    repoURL: 'https://charts.external-secrets.io'
    chart: external-secrets
    targetRevision: 0.9.9 # Use uma versão estável recente
  destination:
    server: https://kubernetes.default.svc
    # ESO é geralmente instalado em seu próprio namespace ou em um de ferramentas
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true