# production/argocd/apps/platform/5-reflector.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reflector
  annotations:
    # Wave 5: Monitoramento pode ser instalado após a infraestrutura principal.
    argocd.argoproj.io/sync-wave: "5"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://emberstack.github.io/helm-charts'
    chart: reflector
    targetRevision: 7.1.20 # Use a versão estável mais recente
  destination:
    server: https://kubernetes.default.svc
    # O Reflector geralmente é instalado em kube-system ou em um namespace de ferramentas
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true