# Values for Camunda Platform 8 (Chart Version 12.5.0)
# Optimized for a single-node k3s cluster.

global:
  image:
    pullPolicy: IfNotPresent
  ingress:
    enabled: false
  # Using longhorn as the default storage class as configured in the original file
  storageClass: longhorn
  multitenancy:
    enabled: false

# Zeebe is the workflow engine.
# For a single node, we ensure replicas, cluster size, and replication factor are all 1.
zeebe:
  enabled: true
  # Correct key for replicas in this chart version
  replicas: 1
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  # Pod resource requests and limits from your original file
  resources:
    requests:
      cpu: "2000m"
      memory: "8Gi"
    limits:
      cpu: "8000m"
      memory: "12Gi"
  # Environment variables from your original file
  env:
    - name: ZEEBE_BROKER_THREADS_CPU_THREAD_COUNT
      value: "6"
    - name: ZEEBE_BROKER_THREADS_IO_THREAD_COUNT
      value: "2"
  # Persistence settings
  persistence:
    enabled: true
    size: 32Gi

  gateway:
    enabled: true
    # Correct key for replicas in this chart version
    replicas: 1
    # Pod resource requests and limits from your original file
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
      limits:
        cpu: "1500m"
        memory: "1Gi"
    service:
      type: LoadBalancer

# Operate is the monitoring tool.
operate:
  enabled: true
  replicas: 1
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"

# Tasklist is the user task application.
tasklist:
  enabled: true
  replicas: 1
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"

# Optimize is the process analysis tool.
optimize:
  enabled: true
  replicas: 1
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"

# Connectors is the integration component.
connectors:
  enabled: true
  replicas: 1
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"

# Identity is the authentication service.
identity:
  enabled: true
  replicas: 1
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "1Gi"

  # Keycloak is used by Identity.
  keycloak:
    enabled: true
    replicas: 1
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1500m"
        memory: "2Gi"
    # PostgreSQL for Keycloak
    postgresql:
      enabled: true
      primary:
        persistence:
          enabled: true
          size: 20Gi

# Elasticsearch is the data store.
# This chart version uses a simplified ES configuration.
elasticsearch:
  enabled: true
  # Correct key for replicas in this chart version
  replicas: 1
  # Using the more generous 'data' node resources from your original file
  resources:
    requests:
      cpu: "2000m"
      memory: "12Gi"
    limits:
      cpu: "4000m"
      memory: "16Gi"
  esJavaOpts: "-Xms12g -Xmx12g"
  persistence:
    enabled: true
    size: 100Gi