apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: camunda-dev-ingress
  namespace: camunda-dev
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    # Se estiver usando Cert-Manager para TLS
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
  - host: dev-camunda.seudominio.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: camunda-dev-identity
            port:
              number: 80
  - host: dev-operate.seudominio.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: camunda-dev-operate
            port:
              number: 80
  - host: dev-tasklist.seudominio.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: camunda-dev-tasklist
            port:
              number: 80
  # Configuração TLS (se estiver usando Cert-Manager)
  tls:
  - hosts:
    - dev-camunda.seudominio.com
    - dev-operate.seudominio.com
    - dev-tasklist.seudominio.com
    secretName: camunda-dev-tls