global:
  image:
    tag: "8.2.0"

zeebe:
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  pvcSize: 8Gi
  broker:
    resources:
      requests:
        cpu: "200m"
        memory: "512Mi"
      limits:
        cpu: "400m"
        memory: "1Gi"
  gateway:
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "200m"
        memory: "512Mi"

operate:
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "400m"
      memory: "1Gi"

tasklist:
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "400m"
      memory: "1Gi"

optimize:
  enabled: true
  resources:
    requests:
      cpu: "150m"
      memory: "256Mi"
    limits:
      cpu: "300m"
      memory: "512Mi"

identity:
  enabled: true
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "200m"
      memory: "512Mi"

keycloak:
  enabled: true
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "400m"
      memory: "1Gi"
  postgresql:
    enabled: true
    primary:
      persistence:
        size: 5Gi
    resources:
      requests:
        cpu: "150m"
        memory: "256Mi"
      limits:
        cpu: "300m"
        memory: "512Mi"