version: '3.8'
services:
  camunda-dev:
    image: camunda/camunda-bpm-platform:${CAMUNDA_VERSION:-latest}
    container_name: camunda-dev
    hostname: camunda-dev
    ports:
      - "${DEV_PORT:-8080}:8080"
    env_file:
      - .env
    environment:
      - DB_DRIVER=${DB_DRIVER}
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - CAMUNDA_ADMIN_USER=${CAMUNDA_ADMIN_USER}
      - CAMUNDA_ADMIN_PASSWORD=${CAMUNDA_ADMIN_PASSWORD}
    volumes:
      - ./data:/camunda/database
      - ./logs:/camunda/logs
    restart: unless-stopped
    depends_on:
      - postgres-dev
    networks:
      - camunda-dev-net

  postgres-dev:
    image: postgres:13
    container_name: postgres-dev
    hostname: postgres-dev
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pg-dev-data:/var/lib/postgresql/data
    networks:
      - camunda-dev-net
    restart: unless-stopped

volumes:
  pg-dev-data:

networks:
  camunda-dev-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24