apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  project: camunda-platform
  source:
    repoURL: git@github.com:Unicoon-Protecao-Veicular/SGP.git
    targetRevision: HEAD
    # Usar um padrão glob é mais explícito e confiável para o App of Apps.
    # Isso instrui o Argo CD a tratar cada arquivo .yaml no diretório 'apps' como uma aplicação filha.
    path: production/argocd/apps/*.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
