apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: camunda-platform
  namespace: argocd
spec:
  description: Project for Camunda Platform and supporting stacks
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

