---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBjM3WjaO8HtRBj+Mx9fZC6yx2uvZSHQHujUyNkXzvuYIixBziJPrxJPZ9QH9Ah5vPLeP3LZ4jIjmnTWEkp7BxxzDIkDtyZLyGfMpWWFZ9kZ+SGYCoRUopXktpCZmAsBU4559RDpy1kz3HqKmkvo3u+PJKNTnacGvUosdV+bW3ujbuYqRKJasu+qfw9f4HSJCIRj1zBGTev9Gwuch+O6heC4pDeqQmH1Jg6IG2W5cf53a25KdDv+deUOjFI3C9CZzAVytdgxmYYxrMFIypEvJMouQcMYNk50JgSMm2X7eqmc4L0xc2JQBynLMSEfAwCIXIhVjgZX29t28O+53hsShGcQOc5+//d28FD20gTHaUYjVtxa255ctt6Kblu+TRJDNQC5afexJn/LRWtVYYhIbMGxZjJcbW/GYkRw76u54/CkG62nTviwa48XhFRoHJoGgowXTym7KXk9pEnPKuOuXB2LXMs9tKH2z/u4U8e+RF7WiKWFk01VyI6n4105gG6n0n3o2XxQQvqqs8xg+YbWOIyI+k65P4lG2164BgPVE/iCE8bB84rhqJ58S13QGGcjPmC0U+WSafsUl0D9ll72zcb2r82Erp7KCDCAdTgaksn+Wg+dhRlvY/LPFhfkqgeLa0cciyj1zfieswMWWNIiS14g6h3adcY1FFVNt0hV3iJxUk6UAbK/R484kQOjIsWNpJRI6SPWMsPYmZmk78NYvI4IXo3cyeeNt7OeUiASNln+Xfb9iA6dcnmigL/Ow==
    admin-user: AgBBDJGj9lFslTsz+iqtdMDYiZY6RiBq/u2dcuhPhOfo78DLScpCM49e6BVoMqHQHCtf2MXirRVUnJzEY3ASdt/zLSsvyvHVDk7WAftYJ9G+azsVvnfm9L4Pd2yEcgABPtoX/EpFrbDt4i5GvuNv1eUjjyh9UUmPJxNegq4RLwMYly0xbKN0jEmvmmYfE2fR33VHu5L5+ioixYSfhbZBpzToqYLIbjcGWdkgTIfuKBPQh6ItV0Mez2i3p30ORsN91FV0Z4so6FFGfGxZxcwp5m1qXxZtkmN+jnasYxqjNnso4uQ+vv9f71Kr1h1nWBqNyntyii0iQCsdtNjWSG1w/9fUviOZD8NUf49X6Eobbd8ha0+3W99tLR3VwjwreiRVYCfvNQoImT4dhoVA/q4JGic7c40gkh1E70jSdAdxZEhyahFuOYsMz9CJEQx6JF6JyKnrH6PloCSPRDzyp0yuS+UvNsvUzjm23m7K3CZhEGptmtYfrE4v0+FA/vfZP+V9KZBp8PNdN9ItFHhbgWRqgoCj2R4DZXGQ5byl4wcwkNjNK2GETAGC05frkWJae8IPUt8OyojtNUtzV8HG7TddaQMyuvW268n+dU4yULmB5iVn7E1LgqYTgAyEq5H2w43qxVNjNaEerhKRbI5CeBpR/VcMmADCBWYiFsrCt3CpHWxTXSqroQX6EI+MRY/jNGDXAxrzFGVE5w==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
