---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAPAge5xmUGav353564DPzSwDWh99zV7eukAcT5Xq5cCB4zulOoNtylstvvzqCayoDb45KqVfMlwriacXUwlNn/OHi+G7makAuD599BRLSF8Ty24d/RBqKFPCJ4/CPrgXZ04sjUiFNCr47Ru5jMC5ee49inASnjcMWXt/trsz/OraVP+a16qCQXiKR4rcCT23OGuc6GaJs5L7A+qz8AA23wCbOWDYHRHfvcoi1o/TY93bXxVji9asydTRcakbhEPfTAu9Z8B3roh37c3qs8mG12jJveaDFXQkr6VA1PQ2xXLpqLy2NKwwOvSXnA7ZWSCK8/YLFo7F5Hl0COnvTySxH7sHec67abtbfNNADHhbKtXXhRRk2GnOGhBgB9RzQAn7BfM3N4pdQpf848AYP71Bjsr6RPeb590G/tpkC0BX3ovlkz8OW3f2H/BDYO6PY0qzy3IG6bmDrLYwetZTIqardYFVjGoRCACfFS33le3qfIZcftfGUuAjyhAw+fKPH/5TTYhH4nciCEDXY05ip8p3eruNn4mduvLte5YwI2ZuRkDemLe04yYMV77ATvh5KrrBH5VC+46Lp9Hj+8w8l4yyhoYmfUZgn9it4dU+OXRzXqVg2yQGb1w141xQmIcfec/0w+GpwMLx3ZevMGBSzOXt8QBniPeqe5CpwgeD8s6BPqp719agkCvCNPuK8qZFs2PKM4zsuUywU7yqSkO0a2/WFxMRBeRjCl7wqInZmND07jq1eD5o7algSbsomB+g==
    admin-user: AgBLpK9eKoHDmfbnJpycAlwTO3UJRL1xSGCG1c/JRDljokiMpsr6CGw/8KXpcZ3lPE7IPa1GLcEAYgjvHKko/f7wzck3Gr3mBZDTnDON5tDCzbbf6OhjqziPCgwKnEDkMTEz4+1PL9OmWbwDRQns9DSRAP26FUDcgv7tu6QkyfqocXq9tWKLB0UwGLonemv6So5MELtbciNwf24cU/hjWUucKq+xsr5aFnwDdCLKn0NC/3RKQjJWvPHWXSzDy1k1u3yWHXpMQLQL7HYuC3OezwWjPmibkW00aKqvJnWZG6HwnCGW4bBQ44xvu6/Ct4Iwy8OS+Wa/eEpzjjhqDcEUtFkEmidsFTcvxA3TBOrsrsfOwnH6lpXg+q9cMemUzLezVF/sji6aE//Rx1ukhl5pbfYVPQZVkrBSYkEIrp8CdHLAhBZUVhSMSxN2a6K0aivp343HZBLfejwMzHw3ItF3nMpD2kizphlOIKN+dfmO612Cf8VqO6ZaehdzNwHKfrACzaKRsA6+jPXZKHLPqHeS6bzqR3uPhnHtvx0oKcooDQY/OkDdk8XzCmOz9eTpwS3YlfS4R5oeQzx9K0GUX3i+320iN/qKopASjLbBChloAlb90wT/iasKOHdE6VZH4l974qO7z916wmSQ04hS0ijeZikjvWHiP+D+joTwktxh8YtIH7EgGuaYAn5WbbSH7wwUuPP3p03unA==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
