---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBAyBsY1Y3mEnc+fOZEDhpQ8JyixZzFCfxiJEBYUMw+JdX3xjIx9tQEgFi/IGlajhA/CwLTUSUmsDkoLa38PuYq7NyEDDRm4Kz4K5d9XcWayNN532r/5Z+eKHodBSxqTyqCYI1KBA5ZW2ebXdbDfwWGW3sw/gZ41fIvyn7JDwS4j2IXveVNwuoR7/+C98u30JPpNkzTO8aIvkM/V1BzYhuHweft6dJWh3+GKKuNJfgpavi+B6aVRTwuG7CI/5Zy6t+bWbWIHrVcpBArbOf0gKgTKbrw0B9w73VsIB81NMY48lSGxId4Rv3Nx39bwPCMISO7YqRT/j4RKoHFNry05xo7K5Y5XO3aWsPz3ZUnSngrmxYGKcUpHSxHpNt2jP2tw2L0Y5G6T5rpIqId2EseWNlmJLmt9TZ/TUUVqbNRo7dRJO1nxgedRttGX8Y5yMkfTLaBDKI8aPiQa3btpWCszVThnUFdfpig4y0IvlWDk5iDkeacoMsK+1cMlAGSS6sXWHNlnENEqW38FdcMIxA0WrZwySg0cQEAXyjj0KNQOX95/pWANP3+idobGO2joDeMfSN07PqJxRsNRbCawsHb19da62dmTXJJ13FxCXhtJpMQH6dJfG84krrJvA0ABwKoxsg33JKp9tfJjKnSHe5lFt9IczNeycd61bwGaiB5bDCPkDkjqEEkZXpjUlzhufvWVl8xgnPsvOJWQ4Z1QZa/lxkAeB924jB0osZ+ClgbD57p6O5mkv8na9HS+ld0TQ==
    admin-user: AgB06xk8njTl3OjfCeoLWioE/YJOmreFwNUAS2N04OdLhl2QDuYQvHAJrulxSXOYw3rH+OLPwrUvfXlqm+oPxTGMp0aQRkqWO02ToXbYGi0OKvDiWAfzOUdYRqNYhq5zVMTD5mz/hSw4wmP/j5QxGTEcEN3hRY8G+AN6md3HZTKUuf8iRCFML7ywKoMKtU60+8ujRJo8Lc6jAXUutQqpUrDGJ1LPYoAnx8Zy1hXWzkerGXoZ3lxaGO0/v1AMSJoKtULqyoEagYyZ62RPCYOGj8FZY/88DSoomshvFwKqjL4MrDNENW/m/ySK3s00OpTUgeH0W3KuaEBLlGSrm0YTxyz3JVNkAcoAnZQzV+QolTW7IJtwbQLJ5ttNgx852F/fwS4t3pm237BtS4gq/+wSiefIpAOT7fvK0llxvQypHJudNYGvNmCFSWDYub1Gc/q7Z7naUXqCZonIP0AAxVVK8Jc6eNpzPqpD+pvaDoN367QIg2LejSaoYC8qlaNvTSCC3xOxcfZnel4FxDmkzNAJkx6/5ZOj0pzMj446hNu2t0kYD3VcS/uU1aaVmuDiMxg0nGtHv/CY8cU8EO4Bmbb4CvHCRORrbL6desZivnthUwPoG/SErIlX6M5tW7GHm0hq58GiDQ0PqbOeSIVax1mgvWU96ogBKvudG0tGm/tJ9TnXI+uTo7jR5ScAYGj0SZa8Fd27Xf939w==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
