---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgDMeMXwNQlvkdqaCqN2kYasLIDX5wJTZGCK4jF5TyRivfSu6tMWyxDh/iNxTJsXckkVc6j6fzU/WVJ8kJ2qVeN6k6o/SLQlGR8E+FLn/oRoasrbkrcaY1gNZhckPkn7t0W4n7M6ioBFL7USVmElj89dsKIJgXhPGuK0J5Lsvsj9Eq2tKFpnFWFgk0G5pJ1zbBIjPV+C9fL1ljNr4Dfrsu2MNMmHdxUCeasR/4eVKBmKuJV0M82Jnyo77IrMqNYLLMKEqSus0EYStvcbMjQhs1cWB9at/cOckNhYhnHea/5pTGcA7vK+xVeotO1JY+v3CqXA+t61MJzAo3sJp9HokQLK7PUvrrUp5fTAOPJSpNdwOpdQzwLE3R2yAosJQdgUJ2n9BvaXnez0wcVRes17io7ZGxoH/Iy22nonbUni7mYSMXM2r0snzP462tGSPQjvTgLQIr79Y2wVjZ4dE1VbgM4WpD9gUsxtg5qKU+gVbLKwXEeEFTEB2JniONs3FNHVm9zbF8eKOqJiL3n2lCCWn1n/SW+VgfFJs8scZA5DudRs99jVwPvXXVGJVTbcKa6t+V5r6QS57W5HAvUF1LE4kYgeIQeIlFE+/yTnAn8r4fFI1xmp2/rDBlFRER6SbEAqB08WTl7bj4jAsV3PPWqWJFTj1LhjX1Waf5MCFZ9au2Vz22oaE0VWx0yY9NPTrGL3F2JXl2V0yMArlX2ZsF7DWkvq6Vs/wKhPG5C/aV/0G3TCk9rxdXQ5hHJTnktVHA==
    admin-user: AgCp9Kn55ypRRxOihNIwhvs110J2Jq7P4bAHroWNWMcTe5D7S9bFluSS1QVAPlILePOGd5UzMwEt9nG5xdupuZMu1zWzDwY08lX2qkSp+FmF+U9Is2syf7zg0VVUrE+dB1EHc4pqNas+cWqs87B5lAHBr0tPDDM5KjmrqUcdVfKF5wY4AssHGQi/Xu4oY6X/GWkXr0UDkAeQS19cyzPcF6zYoo75EINqb/kRCgr8nfsdY5FPd3Cc8ndZ4jFwWJDReGEEB/TIqBWWLdA3PPBH0aroKF8xQCN08lvDNc+GGnF3JNtFPlNLWYyj68x7qaLx2VNvVHDG+C5rmFUufbtn8w0fRwDWO/DlpAGoAmmTwYeyY0ETd7uZRSKVy/lXu7Ws9QzEgORadMD/yH6+368RgK7sGzkHe336lj9q3j0RMY3Bfw4q1LyWRzVLkZGHRl/B90xCjtrd43cUN2uOMoUBggaYsTzCEz2eBikoZbXaeStkQngH/aSkxY7RnL2OBsY/6Mu4/f6yGLcIYhEOyaebVyVMXP7dhceq6+ruUrxd9RZ+cLo/0BHryN8QAk4zESnVSUivsomRmRll/HSKGC1VoZ4InRfpqDKV2LZfFQTy9RVci8Ao9FVLNfHXdhySqAt0cDdEbiKxD5SGJfVodDZsgObJYGLnTMA47kC8MXSpyuQYAEMXCAzwDeQhTLaoChIPWusIPWG9ow==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
