---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBEaW9zCISvgtDPAhDNXPflbP6mymm8jNSvkI42mznDxeYAL8p2ltLzDa2Y/MssXk4US80J6ww1j7UdIE+zBJIAfNImhICXzV76TuqO+GSCTKkTpeUcSTjxRD9Uziv7aM8yG8dUyzjfDxSh4jI1YQPrJj9L5zK2E0MCEh4UfWy0mGGE/SlLO7g7XDkpk9gKRAlDlUXU5xRYBRlbVoBAAmyJAKQLg/vOP3lRxIiivOUa0jiGoik+jNhAhqJSr/1IrZUW4vWqHYAZeIA3cPYiQoVtfhDMEdO8+Do7DJ2530TjaW6zMeRsUXhYWIcxysZUbGhctLP2elr3gmxKE+mqb59P/FIAyuHiWYCeg1pEmaiw6xReTpan0h3Md3hUbZ2/kzs0nOqUgP7+bpMLGUArUJY7+HnhoocX2hvp1eU9YeOpiTg1hd7tCqbEPaXaadJMLXo1aUlNeqxIHi52xu+Y34uigfQA0aekqoWfWvPbeRAzQaC0mDcan6+htEzBON26GSN8n62vn+JCxsmSiLqKnIuRXzfD4FQvaPQx+XeLbR2A/UbZVeHSF9pxaSsj026cZB3mtbwQmE7ZVzZj4n/RWuYbRltS3oVKnO70XyHtJLUqq80B7Bm2N6T6cegq03fDGwYux6srEx+vUutEbHQkiGZBYXUqISIFbKYYkWyOJPS1XxOWsqToPowc4pjJ+qc2+ufH1i4YAkAjwfNfU4/NK7RoZSi96fFo6gQl3zfhe9Z1Fet2bctwt4kSgpR3gw==
    admin-user: AgBFnQt1lfwkjCNnTSr0Nj4Z0wexnH2A9wdRz3PxjlznI7hWozoLnlpia2uGYYVJHD/KokuAwWSRQac5/eyj241CXdEuQPQ3Cgge7tZ3lmvDQnobOiBw1o1mhdTzbZF8471wgD3IxahlOIDi96v8dI/S+drSgf2+BzioAtA92DNAaVvZ/wyK0LLkNJFHJP/saGV4HjCfulYaRyM8W+XEnRacU4vTNYArUy3qSeB7DuGNGWRjyBWPGYASQ5UWqiy+91Hh1gZ5j+urQNPGKnlHflpyinhLTwDLA5/0gZiMTaTpUdaBCEsSnqRNlewo5M98pr/+PaZ7rdTvede9pbUsj+3vx/J703aZZBsv5CgrSTKoxLqjtaW761ZS3euG2/GHdaDUJpAHInqzRsn3w/t/dMalbxS+SYGiAtBXgcaEAwmKhjdlvrhcL6YnZ4AGP7N0lDYhvbbpC/+kOpJ6iziN3iKjtYRQob9iHYhwibdmwbhtem10m2DqSwFi/pZOSkrzCJ8dxBxSsvIlTsZFT30IpD75paHLwKRp88EKDDn3YnuDu4d3X/6UDNJo5g5F2wjzU8TaH2QqxIAeq2gCH9dmV7L90gQXCEapV9g4s/P83N1NQ/L+Gvtt79vGD+k3azCiTMAREbqLuJjqXLnlgMHOHXg3gLbNACxT0A2wPGRvvYs/67/2r2JOWY6aJiBe7FLZqQzPSHN3QA==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
