---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCbhQ4avOEb8FrXA7E1pUlKHCw3Pj4v9uWfDgZYxrp4QqH89KGSvqM9NRjj/aZP9adpMSYD2sVuIYBluGeoRPkPsZ95+719t7UE+JaxYJkRw9LBdn6/58gdPLbGFyYTjJx3W0lBIPnVjZVMd1ptWsxSB56QOTW9WV631yWwlxssdrs43/S6rSsl588pPzY2s4YLnfrq3OZL1KioQiX690aRJWi2pgjomZfBBnlt8d42oc8PT4300LWM4s5mDbcwKd2wSJ+9y5/WHB556MpzY/SqHosrYcnuhq0bmVMf5nkFcyHRZFfGn8xQPq9yjaTZkIf5uTBKlF3Qgq5Cyq1D5dz/P8lXridlRTckUQ3/DbsW6Z8GOXUFJQHyITgpcrsdoGxBRK/XKlDxZYQyB/mZbaOuJ7Wmkvh8qHQQBeXM/DRe/l0dbZaJbNspxitWXg1W0+pYH52wJm/7pCaNUzD8tYfm8e+QsiVL9EAHwy2ezThJ1XcSAKLBMgIVkZaQTAMjBK4JYME8h/dy5no9BGNi53+jgnESkcabMywiL5Sox2sPQ1RW8PfPan0KfH92vUr92jls/zSoZ3DjiseSGZQRHKaGbByz6cTLZlyEYuztOuXfMEYT9bCf8u9GQZ5HjxstgZhQQyeG5wuvX4uuD6C0GcPT9xdppM5YaIb5l1KfnOP5iup7sAmLp3xspHOT8qww+wNTbGLHdcIhYF3Tv24a9C/MgqOQshwtbYq0eU/CvzUQ1/gTu62wb5iADVzkYw==
    admin-user: AgA37jArqDZGsqbOgCdVzuj2P4o5e6koF9vOHaxmIFC2LK8RXwKRZL0Arqc3VUBKXoo8+60uDUATgBLtLX49X8AXY1zXemyo46j0fYoTpCasAoeGUQrAOPrILPeiAuQvLMSjxdC2U9GaApMwiKtg0C2c+POLAc5TIN0gaxuh2QlHvZNGWnnejkXVtJpHQy81sRi0DF0nnXX0TgBtIkhG1MNbS9tGkyTGkVooO2l5uxuu3hOMd2SwylPNB+Eu65u9ABV9pu61hzepdMLoXBw7mua3ri5d0M/BH43g04iCrlvFXKU4E5ndgI2Zf5whNIbrLI2iDeGrkq7ErnJIeU2IQhpWcKIPyD1Tdyzz9n3sRBYliZdPIdporLcEV8tG32OuDW4IjG+auCR63aUxtJYDrsp9LnrgZ9K/sPLIf/TS+lF3/WieP3WsyI4RO1L8WsKCJtTXb5b1dtghUu8sLy2HnWhkjGOzT8IOEB8aYZl8hURN937TRAZxkAnFBMSy1DGlDR1NepaHSkyG5UCF8unoK5OgiApYF8UgWum0rHAr7fUgZgqJrhRiGqcdDt/uvWPEpWPW/BsfDMmdnxU4qdClAoV7uA38hgR5Zm4RF7IzxYV3KXp2K3nuevM6khM7r8jDmBhAju+onKA4hiRNCYuCRtGp9KyuuMnhLkDq74R5cDz28VptIRW6gK51SQh+avWS4m2OiTDV1w==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
