---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBacD3gKzIMC18sO6fn2rzTcSiKUHfpp2qDSqwm9Or7cWqOHlvOrELn+TFuPX7B4qrS2rXYnSHPcaiEcHDakZyzrw4Tc6ghEQiEd0bGdHBvrPZstnzQ9SgL2B1zN1d+AgjrGy8qxQbb3j4sWuYSNNR+WP3d7x0AN9eohK8W6zLXhd4R82xbybyLndCpAEpims5qEPFmS0WFgmsMfe5prOoPaXfigWZBzCGbeOHGKSlOrJzThmd0foUicIlhV6JoTacQzkWuYob88n/zEhTgBdGuWFbTkYQr0toIdsoKElNN+58Cr+3kcSr7u4A4MhlgpEzriF2Oc1rOQX+hGhRVvh5CRJeHSeCeyyMYtCwhc+vC49f4FrYPDYyO7xZrwwwiN52h16Vf852kF6/4sG7oHKhfPXFk+2EAMVnZGbi8oGHnseBUGCPNuVcmRFgsl/LRmaHNXZoV/ePm2Uc6uyE3wXCfHPGifmInCPOgX5aJcyXfvzq9iKtk5VC/0/bEm5ZOyhcUogK349sa7Oedw5XE/9+POxf9U3c2OnQCtQQ22iFHPikt2CTg/Xkde1D/i61kAOWQbbCDE/RQyOBs1mmUvgvmbEawVkM1m9mRUtyHmunRP2Y9AFcmGx23Z3OyJZn4TpNoTUAz7y/4NHnz9YQQiW4iYxHifTSqAwQ/zFDw9x5hX0xNo761I0IilcxHrphwLpJuaA2TRfLOtRzlyfV9FUiMXwlNzVJ50iDB9HM3RSwiUBUwQWy1esPSgoUHLQ==
    admin-user: AgC1jZOnmZdtXUMZsp31Uk/tRs7qTKoSpwuVi/XicKcldjl0P6nNX0XRvVpzENFn099Fr6PlNxz+mEWZEF985CINcYDc1bbTpsvtikC5mkzm2hpL4XhcipXVfRpgKrunRGt4D5Awt2jRdQ/Ki1pRSgVsEetn7Q9DD2i0uq75z6jeRp5aFBDEJQWhRoWumr8x6YYUpR7YbuHQhevmAtKlRUrG1wlxnU1JHOSWwVRzjcm74hEdr2ve/XN/czmFxs4UoN1MW4isZcCBtKOZoN5ulAMHP5wJJLJS9yjYsDwQO+bCkOrqFfhJks6o/Qk+Zz5PMf9IGet7kZre5OZGX8xoe0wSqyTp8crOsy8HbfjAR/HKHGDAbZ7tE4SuNg/b7uQyg8+2j8XVFm1uLV+r/r7UhvYOYfsccem+NALp2oWTQMG1Y3sTX/f1yyt6gDoqCHctHv7CjnkvMizDD353Pe/d4W401gtVcLbBN8Y2F6fMOGS1PiiB0gt/CnkOYEvW4wbf4IlzY1mowVvP/vBcaLerJJl2I/H88hxZFflW5nuA6eGTc23F/lEj4IC7E7LXAA+cMxnQVqpAYs+ao9ZV5gKcgLoeoySm4CaYDrXDJtAskGKY26Z8GnAFZ8E9KEdyGyjcuN0MZUsMmK/AZqYFiukGrvSDp2j4df/YH3a3a9onh2PIrB2cNDAlOvN3j28kqoYlHK5fNKD0Pw==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
