---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: camunda-pg-cluster-pguser-keycloak
  namespace: keycloak
spec:
  encryptedData:
    password: AgCa4r0L4TL13mlN2UpBiyKyKF5JR8y8rfKMhFLuGtrKDa8jFHXd95pJlSLeVjkZ8sQSbLBiS1Zg99pVdE/O+7WZrSJHcsF/YnvOkqQg84dlof9gkejTJl6NJp5M/B90uPF6nUoHBsB/sggvcAFxWihoRkxrqZmg+dz7b0UMhumR3FD7Ij0A7XRAuf3G8xbV0Eh4EK7KKvRcFgzkcKJS4XGLXNPdir5O01DUhzWrBwDDAQAOyGDC+Q+2jrYdOE/nEjdC4qbieR7/S+0zBHanOqJ/ydkeJBx+28civjE4djH7DoGOH1aV0VpdTXCArSZm/bs2awS9QRulf4E/78JoweCUBdN8Db5NuqKTVTbugIl9jvBFP5+vsdr4k0Bv+9wlVxBmGJSCt/oTY2EdtkqCHVxRmtuBpCK3JSMtvtKdII0Jss3r5HwFAi+ML/Dq8NO9syq7hqDqVaW+ZjkHLdPOsTbt4LBaFvuP/4upAF2s5WbdWBcvk9UpzafTXAPEAWi11m3MJssNuXlssHOvvLRfNPclQJiOz6JxetIbht6CU4iZzPnYDfDiYjHXIdVUKTiAoV9ZlbCFDtf2c/broU/oQdaHaplIistDuSqOobO6EfJrpmPv22vvi5VVlxFULdP0MJpr8ZGdNtOJxRzyfccNLM+tz2IIi8Z7FtAMi83Po6MJGOgEweSx5RGm/cgr5NChcXyeFXPWu/evOixJFMlcXwnKRSbgkzLBNOzzS12yOgHOUTwDPsPDRzOWAoRh8w==
    user: AgC2T5xGl/mc+i2oAKQgZKXXYuwawXrsHNcrxNLlSgPpBBIX27Vx+NkKXdGXD/X+LeZWbns5FZeUyQN4yD6QuTvSiszR1BGEqFxqLWOiOZra3VjQHgyvRFUVtYJG2VBeRvLzInKJD0bPMKn6H42ST/jqK1KVrzeWbvhjPzPtCTwhl2ieWB1M4Ibcxza34WaDjunpZM7jy/mNmP7FspTEk+XGHEIgbAtBPfUxg1Zl42QH58blS0BZiWe8j24E2RgsuA7+BXJhsUjERi41KLo39roYy2P0jLVBi2o3hpBsrWaT/uQV+Y+48Gd7SPtkAcsagHsgyBcnjlictYaO/jxrreKfpN6vsp8vBLfGKadLLDvcO1Ef6SZzZZHFDrFRCAfHTI9LICAEJ9xJ2Ohkh1SIpP9evyTQofB0yGwuOR5qanc0xivbvgPsb+pBdgUDpLhseneIzPCCz9NHTD6U+MLcoV6K5U9QkNsQJYC+682r7GamPOzdydnG0KQ6ii8G7QuWJ7kx58dxkfIdqvF8vE0uhJnqYvY/FdAwdabvrdwdkmcBP7Fu8r52dB+GYsNB2hEwqtxsUFjICndaWAOGibX1hlbVI27DfCp4yVUJFdzACGAG3cdxq/kSczLhRwQRxHwCpzMITxoyPJ9lyaxbnUcTALsPbNrCFT6WHIndmrml/sIBLKuks95dqd6dkJHA+1pVgt+AAdQwA9v1lQ==
  template:
    metadata:
      name: camunda-pg-cluster-pguser-keycloak
      namespace: keycloak
    type: Opaque
