---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgB0busaR8Q8Bhdo2L/xnlK7qFRi3e/V1/tB8lT0q7wALNDZLGOI3KJVp5lQvSAM7oKkGCN8WcoiqLMFnEUjnE045msZYKHAa5qK5ZXUF4o+1zq7cN0Xp/UPd5+bt4sMeEEt2PQilx6ePnD4SixJCenCP1tt9w6HR5OMhBAlxCNTY/+UhuyKUq55G0deISryloT/+Wyj1rghBy+OWfBesGMvDA3Mq6yZ9BRklT20ewCNstDpJmjiyBhr6UuF3FoFetLZv3ksgV4E35uSYqd9QyYeV27J30cEk3mqL9fHhFkfFu5fy3LgHSwRVRRfajgS7PtHJN67LZwG9o8SLEMBYk9JQUcraKK6OQI6vHwWwnwfwDcKzKF08nYBWnv7wXnVHTGZIB7CwF2BLWIfc419VEpPj2CFWFwbzPp5nooTjYeZbcjSEYlVZpO9Q/xO52vlY5jTmbaA6428z+UiO5dRwXPTdFXDV5LZZTEpURjMMV0Tlc5n8LygBhLAOF//8Pz4uxtqpaRH2hSqZml2YVMv3SljckR+Sr1FxzjJNGQL3hOfkylo7Hi7vac0FGLqhG1PMo7GQNyf6kgmfUwq/eMFZx/6sMSJNAm/7GbQtNPVPYpxNWLSM+W6eN05tCz7UgxPxs+pmzcqbh4KIWrlGWSvrowCexr/cWmtcVXCfZovQCMRIr4zJ9W88HRakPd57j2r44ydlwH++mDihHJJWf7dcNnFloh7cOkxaNfUJeFQRfoMhiJPJOCV1sVR14kSwQ==
    admin-user: AgBPqJFo/UCvuLKqIqecWuVT6mVbavk5sIZTl/gVyW2ePSy9AzDuvi7WJKRScJ4+1h5K+IhJLvSejDerlnmVGTkiQvPLhJbH/doD1cxYs16tTeYOq6JBh7NPh47q5FfSYhEE0k1reluPMQt5i+f0qx9Yhfp4fdfjt8xKIYkH7rwNGsKbgn0XUTkmG3bYCxJ8nUI+ysu0u3lKHM92kyrcGrEW9UKocxlf7vfE3SRZTLADj5ap9n98qqxhpaFGT3/YcV3X4LEN96oEjVEv+dlkt0hotTjFVZKmUASYnNLqaMP7OxgzT2nFpMpdmPimNNhGwn1TlKjkVV+BhWDJ5oPq2tALdAVrfFKTbHqtWiVtuuZGXenn9AYO09G1WBHvyI93ujKbNyeQljNJGa0KWIvPK2u9dYCjuOcdnyk8zjVl2xwzVqQS7ncBUEp2swmpRv2inQit8iP/vDl6pgE7KJ17pgItxgAp9gLIo634tuO5lVDoSmFDTOEraLSfYJbj4yunZ9oM+rfuC0U7otbuXrB1Mfl+WJF7YkD4rq/c636cBWZCAvyMJmDaIgbS3XlkvRA36F2uTfZew8kIO8UnsDwl7w9HNn7pjRMODN2SFaIMfhDCoIICIP5u8FpEfOx37cIgHSie9fchNBTvw6x3ZKOL9g2d0lX6IvIiEJ1QsV74QLzMs2pxZP7wJE0zaZX20nHCaP9dwqrZbQ==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
