---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-db-secret
  namespace: keycloak
spec:
  encryptedData:
    password: AgBOfIbTN0vfoBFliabp6X6eTkBViko2MDzttNnElNWRW5Hz+7FuHmuW2JnOh5v9bBKckJGHhGZ6fH1qdddhdwOsiGAPehJe66cq3GYUsnOlVCLmnNn5XDbBgLzqJ3JMF4TztoDbUjIJs+ZUmWbV43VDOTzuYvO2gfNGmc4+hKABvzxGqWV6VkQ0nTwlhPqtxod6wNvunedOwEmRDGNcxql4eQuSOOAvy99j1DWkDFwmhKBxILTr3UVpWfZgJCEM5wZAAD9dx9DFvIpy2pgXBn/jixLYmXdBYorB+DBV83DNUkFL02kRzNqdEm2C/+V8d9/x63mh10POuD2IS+1cUWYpLGSkDDt8cf1FrTDSbF7IQwtGa4mJkdqhbNVldySwoz9rVCjcxRzVBfwxrgb4S82MXnC3xWwJgi+yjl6ejkK0P38ytv2VMRlsUVHfoW71l3J4NoEOQZQrVnG7EoGyMNf/nVTStHOjUcvaX+S0JF87jSO9qE+fA/uRW5nBYJr18CiBdoS6iIp4Y1hAsjCtyKG1LuogWfE8uDgobhUmQn9uicmsoceDNf3D8o/xank0s0lbi0FT+agjSBXsZOXXPqfzfqLTJ6ewp9mvEVfQ48/AJXquneqhSnJlLF7q8ABnFxPI/TEn/JBDv7qIuwicMayzit85F4PuX+noS8WeKGTNX/dcrSDyTXIstccQuO72mRMNoG5K2eIv4UIRR1dlzlzAyzHNRBobWeZQULJlew4PPztSg3mLQ6O8u+PtVg==
    username: AgC8iGxlUrbdYAbRtcs+jm2fOvj6tNnihBR8XDCVIoC1TaiutBaeyElhNwwQqG6mVbkxc9sisq8bc9jtZ/4USLtLgmzUN+zABHkKraKnywHVsfB2iZYdREiV3PTWj/qrFXcAqx6IDeyuoM7oFWAXcAOfNGiFS6BJbO6y9kPXyNy9cprbTrGPtmHKINss1l0TUBsxtu4cNsngP6nvXcHE723pV8+aCZVKCgdX61/STsFKQSQ0U7NLKEDNmJfbshunjsedgyYvVaPIKoWSX5FFwenUKeXdz6I6Tejb0WJnTJOs7GMDQN3S/5c7xBrQ2pQULlM/K6QtbNAgWUp3+waNDqSC4/XJSuUx12sHlR7XgjY243zgqeI6CsNZe6TRMfxfKgycgV4SjhS001XVO6AKIAV8UZj3rwQrYrYy+fYYtQExFWIgrCZALCv7WQC/jhJkrvINoYBrTT+E0wTiF9FgGVo5tSFiQYbkqPcpI+dUcRqBLtiMayGWUvyqvcHvcbloUdpBvCjeeRwmhUo+AHm5MCNnM5+Hpple5sgqMx3dGcOSB1WJ+uBdNWzuOdINPXh4PvlVHUnI15MMgWTyulhUISnZnCL6PyNpRg8GZYy8LZZpJhw394mHET0AGWVbw8zrmWEWudhOs+lt4XS3Q4oJT6oO92nSe5Vfadk0ZCj+kVHbz8HvFEJFB7cgUnqxMwaskZQJORz2S3TeGA==
  template:
    metadata:
      name: keycloak-db-secret
      namespace: keycloak
    type: Opaque
