---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBNmBQQRI9/+yM036A5NYsIkTWMvI8tK+A8oAtFCEKvjXoSPU6O7LUp7a55MvxzShgfkM6ZNo9y2gJ7NoFXpFZDKLe1oO6y3XFlRQbCmAq2Pwg23Qoe1dojb3jUQHzQ5OFnoJeqEcepEwj4fqg2wKYrXZhWAIkJMBsiCIXpkA3mtiUEg++IcmFkWLFmkRRCk9o7clsiUqFrfXR5OQFMj7OAsYCa2NlIJ16TUqucuiJ5Lr5AO6Ky1Z+/OGPNBGMi9o7qKWrfKqAs3r24ERofdNQN500IW/f9xXcapOHSw//II2N1x+LBAVEeJHjP3CXEnKcuiYWqzOSAI4xBIYFDGBy2WJnEZ0OibU9BH2vx/I6xiVxrXLTfZBY0uaxmvmPRzb5Ptr8+wU/dPowTzNPrJWuE8P1zRbHMKYRHypjK0F/AP1xseFEReQUVX22cJLIUR5o3XcfXFRFW2qOyDU8wGpnViwHo89kDUD4dUeI20va7356GMsoh0yLZXna1SNhfS2LA342AghBSws+kXOytBoFnVYspaR7EbFuqGyA1/JeGemAHb5KjJCPwDfSpKl2SQh5NG5d+dloCtgza0gihK+OfRG5dA3v2NWsPm7TUgVc+PmmcU0Av2DUdtXhvFaeZOxx+RNSX5oDj89tWw9BMses+C4eewdUCIdtiGIDrq7DuMT+m25LDPFGEgcztg+vQjCauBoARqZTgbT553+T6rn8Rt/LVBP6LhiH8vFm8b1vJbePDYxk4/wDNtm2lLA==
    admin-user: AgA5WqPJb4ltkstzEvYCezd+TMECy4MK+pAR34LZRGfA0MImI9RWY2MLLwxv2U6n0z8pOs2Knx5JIJOtIY1IbFrC8877gub/zyMQMrupyVrFaqzqbDM7Bck9s/PmOmJ9bhfKs8LvUaD4K9RGdt0iSKwKNYRP0p176aWqi2bDyyQ4v7PnaXNBQHynAiddgtCr6yZTPZIJxsSGhKgavQBhOwatdeljv+cKJBqQvLRjxRfgyURvU0DWpGHolb3FNpOok0u97dYsR5aNi2zuJadCT9DDKhgySfqt4A17E/1DiCJjr6eQqTi/I9uS7h3GF2nE/KJrI4QyE/WgN430jB8kXss8daSaTWRQqtct8L1EK4/ufsfFNpClxYbbSdc+BEruVbqwo2gmY2ukn+j7kMgwyCzmbLH2u+f0yUKybc86TybNV6y9CpfSY0g91dwElmIMZgEALllsVCIHgjGWJrCaWKkwb8r2QEaPETD9mZK44pSOOhoY/5VUjZbKKzuWrwv6WDZJ3Va7VU7ee1YRQ5k6uKsDV9CLQltTsXQDJoCn3M/FnjBGtJDFxHAOImaBAT8TGgBfjr97RhummHbA62a3rNLO/K19kiw5bRSdo7g46HudkxoqA56byM2nLkFS1bb+88p40IU1oukAoPE7aYlTQS0yBSlL4tU7TqEfMJt3sXFtPb3AEQUxtzpUD85d1qKtGMbPbz46jw==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
