---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCv8jgunk9hi/+HyhmsXfr8P0np49ySSr5bUNvGjAobVe6yK40ea5VFfjDfzHG6tmgLZnaEVepBHyDYVrFRVFxyyLLCTt8W77egmqOunUe3P9jdgWsrwZaR0GV4jiLenFwfDEdoxdiV+VWpA9H6qFaW31+OM3db/GoqSTbxq+86h9g0X3SYHP+GM6GB7VFokfvylnklf4umfi45Crx9vkCJPwA3zwuYsXHEp+YX5DibZgo2gZH1HkvWA169vmA8ZzxogA4R9nAecDZkSF1hSI+gpGKZ9lDmJLwD7gfy2DMBuU8QBLbpeKkIL87Ml8DrFDhQ13PU379JhTUCeZcsefbInanu2k0HHqcVnHK4/rrTeADAKnRLP8Sh6pNaq5+qjBzZE7ryfyu5ILoroV6oX88KCBt7T5/wvefgkCJoQikGQlNmmvwzqFf6ShPcyPIaThKKsB8Jo3KTGrijPxeGK4J2CXeopmwX8/PlMpQm+z3m884KqayP9OBMjRp2Meq1J/bagzXo4anjFck8I7SuryTiOMwOy7a0Dh6DttjmG9vs/hhTmPIpOR4n4jLNf96oz3KQUpCmwhkkq7jhoxe8zVOI4Ls+ZVEN8L7/lxzbk5bWTw6weJENnw5iGYjxG/FCQkxk2/gbQvYc2EIlpXAE6I4+QetbcVRbY68e4Jxem8bhcS41LPAgZ+3vGa5jhsSCsJ+T1HLwyx/p2HN1uIm4z6Tqg1TcQ55sJG6IDVsPXATAWRxwve6fa2rbWjtXhw==
    admin-user: AgAbyqIKbJ5eEWsKCrYalxEWRCZSYZ0zIOBI9uEwDO0xkDjSRe81dNFOqnI0Cbk0My/LywJ1uJR/AJ5Gte+KnUfho+thMOvTyNYyWJPSCpHiug19eDrL/K07yBIWASgn+Xe/7kTZFF8OcZz1jyDWloGZfTja0uvpUz48YN/cxmbrlJjtJCXIFuXEcnUIpZAahpItQAzeGu3j4vXFoV4rDBNNsgwR/ditpXlGBlRFw8VC+3E23pTM+t1ZwyB84lEYw5W/YbJRgTuhrhvUttvdKhvAED3rNbFPvrWaNJ1jm88j88G7Yll5Z0kiB9CNkjCqcXEFT37fiL1UEU2Zk/p/vENPOTGtPNePwfi7cc1hqyLHtvGJKjofS4ewzf+kVGw5/H0CoOFU4kxKLEtM0aZCXj3X/uOWn6tUxC12Hk5DFDaI1/RPR+xstSR0trMOdk/cvctdGeF7WIP9hljxv04i4fJQY/PMPbX3CLgEstudAF/DxJd9kiLxJ0/CztEVx2V2B9eOZfxbsvCbY+wF98x6831o4drxe52TRRUTTMTG/sTzkQvwRt0nU44o5fX3NLY7YbiYwnUNq2OZp1UPuGdlKjWAzmEbMhwxjNeWQxxASJz9bgb4p+cYxfu5pUJodKRyNKUiLnD2NrQGT5GATxI0UovtTZa7hVXY7ud3blFcYwDTrxrgrVowiGzhZVpuMuBL30WTjgl/+g==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
