---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAwwuSm9dkimN1I+WxK5YtQRc9q9zm/oPeD0fnvdaWTcv5jogLnQw4bAjlBJjNccIO+oN4qJhR70f0jI4NnEw1RV0BX+lzN7e2TMUnlu7YEZqMRT8ZMKQZl8AVdK/vEuiJf8F4SGfIKLQ0Kt2cgz13aPoqvWg+ksv/PY8zjYY+L+Y9h2zhe8LnA9VrZzBW72zaB3AqA13nmznQrApa0/um1S8Vns47VY3F5/1mUbY2Y28QKMwjIvXNHQsnRZhAaImDa7Gq9jE6PpCNmJrzsiJZKddrfWuCQcaEnXUBirajMubAMj7oQ/ne6FNEj3wlHysx7UaZ4r7cyzGsVGeiy662ScX7Rvbjw2cbZTLGU0ig9k7wiaS7QSnkmeityE+Veq/7CHCYf5ryUDN36TiiUyFDN8/6ut2Nx7X8uHuKbNtg8LIeenOXRZyKitNuHu9lWsiwVXkn84HkY9EcOXKkA2v9L1F4hHbU7pOW6OjVrOwkJcitTEjAEcWcIhCIhgJ58/dJ8VCpwuYh/UCicVwu1giJ6Cp/sgM4RFHKwe7DukLkgyIuduIvn1nmXCYE8sGHShwzLrCbr+OxGVTf990dbL+Ysolx8JY3zAyRyqkhvNZXRt4HOsb8ffl4LJX57a1u81au2st9wv0iwbBvN8XxpGWHJOWX4GYOgPCmt7Vy5dxia5vneljjxdv+5Y/t4nohVTUAqZfPGPc2UTYhXJuPhZsJBrpQ5bEGFwA8hyU02JfauJtn7r7+4Ls+0GwaaWg==
    admin-user: AgBVHDYM6H8adSuAoEAOthxXmXdb6FXhDTsk3KJxHl82b2ilC/2UfAeXhtKfDRTioi5LeWR5+iDPal7jKFoCV5XEOcERdaMxm3zsQygULYZwpELCGLpBgGrL0Wd74vmEX9VHMRg8X7lKge7eqj2YUilwN7dF0+3S0oaRnYSkCeNuSBIeuABEbcXmwe9u7seIRYvFoHfEriOQKvXBuE0p/zH26tm/5/y9p6uH6bltXCCZSqdEDjQ1fl23Zq1S2cDDmPOs34ohTkR2kz8Skg2hecRht9dIq2zw+MEN0igHSBLISDVpJkM1WojiJj4Wl8ZFgOuWS8DXtZvnhHWR1xXG/MURI63ho0lTsr4MN8PkQU3N7fNg/P3UAmx2ENq/Ib5L8Wwa236e4JJAqNbUhvY4lCXUERMsv8gXSfOrZo8bOPWE8l9W/k+gNT8fQJ5dzRak1GhI7Xy2ukIwczP0BNkYL6dDOn0jrgWsvkoGr5u/r9UH6326wziiqbv57r5qc9HbZnV+jyOjW8Bxkk1Iej68VRUFRXCsD6eZOI9MY5fMyU3m3svGYbsd7WjZG1fhjb0ikPSfuEX6apvYt2ndNLw5dQnoYUfY/l5mdgneYHoF8EJQtJpCmDsxlWsQdW2OwEGhmWUdFe+fzQVTp8HnPpvj/fTHj/syNQB1MjrM0q86w030/FYscMbhaO3s2eNsHWLVYtvrSVq7kQ==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
