---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: camunda-pg-cluster-pguser-keycloak
  namespace: keycloak
spec:
  encryptedData:
    password: AgCXDlXIMuqCOprt1EXkBppEVpui0Cr5j7/hjoA6PwiRELaz+rFsY2BnLOo7HCfUtdHj1juOtJwDfnNPPBcSdi7d2QEsIH+hloGFu7OECjvsG3nuADOMuqtK55zAXqRYu8JRjko5d67ijMXfa0C2uFrzxdYHOPStjHs1dHqjteanAvtj2xg9friIOfYA0Qxz+IvTm4AXn5o/24X/GLl7xlUgOBobHyJY4ml2e4Mp7IYIgrwGJvymVC1317bUMP3JXaNm62jGqmeM9CZm3bwztFgO3B+zcwLVWMbSUArhtGJviJ1gp5Mh7KHhu8Ff1ReXFlfxqTfapqdYYpsZLtt2Ak0x2XPsgbESW72E3QrtpA1XkroArKRh20YSn5ucP6xw0GeGlWX9TK0wZl7509AJwiuC1KJ94R+vmqxlpWj3DsthLle+1AxhOmgn1eysabOxMknKaEBdNOBPb9RBanDd004BnR/pyiC25Jvv8hhQCWB7katKPSxhHtu2mtJNbeGuG2i5VcvtIuEZMoOhhzVvdVpxIDuTP1rRcZJo+rVgHSwFOB7RdU2Q+DDfvuG+NxieuHbi/U4QAqNBtjggsdBJX/qLsIyp/nnXRw2zb/bSh+SU6N2OwIu6MQj9yULie/oXYTCPeP3qtT6Gb4rtGFt7O317VA0RKehwgYgd0oCkUggiPMXwGYaa5GQgfmx85abGtFc5C6b+2Hl7grfqX/Kc3uFtUvsRSM9ykAebaISS25dAdb/BRX+tAew8h6eTIQ==
    user: AgCEbbalQddqzRMdL17gsxMHr28KI9gETXJcOW9DmjXJPo8yiV+j14f8oPSLYpMx3ZC4IsLY0Bq35hXHPNG/b9PNJEJlzgMrdKnShNgJWKuWyUDMNYVGZVZRm6UcPDK01zX6L9J8CisuDH0LXNdZA0gb60t+wMO9+TZ8Or3NJ0vxVCEpVPBFkV/le/eEHFpM+I//sRIknHi0EyprPIThLeQkGwgARo8MYG3ZFPWwsyfXfvxVgdbpUq0OxAbXqFQNsqSrqNKuXb6i2ljzeHMEdgnofspU0JS/olCRM/pTqK69lbLKmKOZ+SuVbcH/ohs7naDeXh62wOgZXIZOiDBQGE4t76cuq0/Sexo9YN/bl7Nj0BAH6l0OVOd+GPbh64aBJ/CyQs0ptx5Z3iAXuImtY34FUpINf0+003jfs1t8Q8neMBMyxPPOkSIkTVqdMB0184hwAfcsf2HkSS6nVPeyBgbfJEtEP3ndNvQ/R/wUB76koLN0cpqKeXiqhI+M/OHtoDPqnMkSbPvW30uCy6Qm137kGd6XMvpuKUyRa+nKmPLnPH8ubL56TC9fapBXtDD/gptlyXaVzJHf3nAxap2KkmviYHegARyBS72w1TvOQebRh0VGqX7D9t4WG858OYcRv524NnARoOD2JkICFn+kLvtMxgoyZLa2T8egPAp77aignZg0YyYiw5oN2ZNcY6TFwWg91BNF8t05PQ==
  template:
    metadata:
      name: camunda-pg-cluster-pguser-keycloak
      namespace: keycloak
    type: Opaque
