---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgB27NNQwmMpnokW9y20WceiGb3XQc3f1U6c3nqCR/Yoelds72CGUS+CgplPzmJ2SZlhQbqbEZ08bFJ6COwtKCD6iyQizo+MAb/eEwHAux94KHpl8qp9VQS3mfaDGyaEqgSL3T2i1rSG+7gRXDybn4KoSiwDP1+c2ywwTHrlszjyXmXpyBqMWT6+zgxyXI+PgGlxy4FqW5g37cVMcw65aDP0ZWfAEc48HkcK+6bVNcRm/QK/PLf7728eQ/ujaxKGvDboeLEWMtePdXMiQ3ZO4AKO/MDYcvBGaAvdrUbUJQOOzWzwohwNlDVkfE2mIJzFNqd/t1/PqMnHUJ3wsCKpt66I9FbxKzWu0DgbmDGV5d/tGXFYj78CT4DG0n8FKrpOvnucgXG/W6YMHHBrrxKe18wgssG0lMm4V2e387Soz1OBl9MCdMbH60zJ525YVrVb7e011K87rO9FqZ0jYctP5iUP2z3wsMahn4I9b7nVCkk6mbSUg3ElnrVOByPzFicXRL3nRLv7lWo6klDnEKGMhjs9E0qQ2xTn6kQMUokzvsKNuL0z+99haL73C6eIftgJjY19aX+Euunazz3tGCz3UveqHCvaPaSEh7c0jmofwnI4DJyxFDm2Xh0mYIQ6Fy17vyJqgjTYfYNkq/I8irapPd4armUPbS+1C9oj6PdKbe3WHMr3FgGyRHS1a9VQh4nFMZ87SzFwdq/+ipvPaBk/HRzbEDjlHW0ErUfZmajJxHEfBz58H+L6ztS6X48o3Q==
    admin-user: AgCfmrF3DrYYF/cSzzhZsCvjRrNzhqQPTQd49rFn57H/fP26T6E8tIeYb+65+p4lOUH6yu8mfyNp+KPEPMvZUQR2r3Xn0Dy7zHpBNPHMIDQ5kiNQXo5p1mSsp0MhD57t99ZB7DMk8GCdaB1wW5/s2vjkzaN8ee9GwuTO38djo2T11rsYAIG5MAhRJV1MnPwojLh41Ri3AThUVEGDWl5AtsB7JS8LOj5wsaOyaiYMlt9armf4EgSZHfLHH2ICwnaX2abstziQqUHkSb6VooTAKMEmSyq0MwltAtldyigRdW86+7lWpYN6RQx4x/hDhNnoM35y1jj1dO95FRQS0lflPe9qAzSs4QzG04OY6/S6rlcnNrmF5x2xseOYmP1ZpU8bHGbM8/PvCCqjJMS2Ps0NYVGKSPBgaaQX9LFuugWSJEfQdMJL9p5q7DvuU3MPq4mV+OdkmuoUN2PZO7kNVPYlziQ9bV9YdxrIrEm2V4FYbYp+gYsvc9kgVV72QeBq+lWs5UAfIo2npVawaff0CcJsIFTIYB6RrSf1cX4kl9JuWXl6Mr4/UsNqdQ9D8knrcRZpZHhVddbEE+mwpNDrT7bIW6Ih3DD+UgyXUk/vOG/NaUMJaVTvsax7Rs6wVYthxipv87AW4kFFUsKTcV1do+v5kwN1xTRhYcTam6JayAUP5vDYlwnvTOmGnXrbtDJDweiNq1CjMMNNwQ==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
