---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAV++VcqfMWTwnZHUFObI6N6m6S6CJda9Rc/tDJEz6YUd9u13U4bJ0EcEqKdoKYNRhlMir5SphU513zB3qsgL+Lk3OAtOoU1n6X+phGLfKgudn9i0onuEB1JwaXUGjorJubGG/7UwdJMDHIM5Ak9TudSUWqwhpLU/E7tDRBiQJdkYDUjcS3gUGVgCwDULsJzAD8+E+JjiwTmtHmlLZebJQZGpD+gZNNNGJloS59Xl2Yg9MpXTW5AClbUK/v51aW/wdBfUFaZncvYm9F2cBMrynVz32l9uQvU06otA9JCg4HIh1+SD/KkLyizDSToRg7xh4WZ48X4ca/hG8P4JEWR2dlsrnFxOhe0TI6O8fiZzHSzpGEF3H9EU1zgVn8SG53uYGyH4IRxhurtuVkLwKwOVOt1mFvXmYwozncxFBn8IrU2qy27jaZWzlk75iu77t2Hde+fBS+cRBCv3QGTA6pA1eICrux6dOc7E2F65HPVqUvUm9HVTx8syq9mHixkXteleMIqUnt4uf4KUcesBpHrB3lj32v6Wt6pRsLZFYSoi0Q1oWJAvUS9PRSLVNNvg5A7inZkMBaLGBOaAgAjLmNdo3UdoS+CivPr1b7frut/ILYAB/xb0whL55XjnRIEReF3boE4TPRaQKGUEOGW4FtKzjXCfeh0doK6BV0TmR6O8wlMIVyj1CnJ3OdkXwaJF9h47QtzQeZD1mhG+FmYbCvH7eyu5a8itLUndKMPWyDuM/g2px6pGk2OIzkeV9m3Q==
    admin-user: AgAgqF2ta/rw1zcdDO+CsQuflR6nxfR7i5f8U3G6cwz4ROc8xmKCxnP8m3N0B8AjxQJmZ6bg8cMo4WFxGYGLUje4x3BTg6KYBZ0YBlPzKb7zs4WliNjHNiAN0V98X7wbhHxTU2MzKXjh9KgIC+2yyl6BCN6wLKDAa5h+6ewbmvN50LT4FR4VBeH3qbpe/Pl/v+EkGE1UZ/oE58VtIaLcsq235+30MMJZnXfzKoYn0/pXykegICgQ08QtM04/HTnQu0GKPXYdDFRrfZCMH60ek14tOmpNbRF7nd/v14iEDOcNHSTpJ4INUXSWaAn/xa5mWAs127eByI606RnLKLDHO7uo5ldCIhDGTtlfa56/b/1VaO5fXNBlAcxtn3v6gdA83AA8K1PnqQexCnu7DqexMWqEqbstPwypWgH9vfQULi2LsqHgapKqF2B6Ep3Quu5uxZQ1aDR9HW5JIq7P9OeC3vXJBoeiKJ1mVYJumN+t8e8veNu37xt09D0iriDgVBAI9vHWB0bKnH06ec2udiSvRQudQpE6e9IAy9A3pjY/gGWaAgSaNQB4kCG0S9cPbH11MexiCfE+9B3lz8lB9ZS1iNLICQ20nPnKpg79em0wI2EiDC5/ihsTR6ANGnomb1ZfSvLIvaGXXpXuSDnNZzbhHiUFga+tenmymvK87E7RWMLFqd759RNSw/0qfShRGCPpsQBiefINgA==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
