---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: camunda-platform-keycloak
  namespace: camunda
spec:
  encryptedData:
    admin-password: AgCNK9FeedrjgBwrBfH6DRLVkNubT9CvVUFGs+2bIvt8NRO63rrJurMm27EVNEdrwciEiMiTXSQfO8K5NKJ/w3/UyeL/7APiQrwoN0kz/8rog7dG7Dj199TvXDHjga03adWSDGfssTalYGRO2B1iHFshgtbSdSPcrukPKO1XpfYtkI+PSLZm/4ibyVcGCoRLBKoj6WE1GU3ybWFCG3bwUarBBJOX/WhLEHDkgmByjTIWZ8QOfRGPAF6TNgLNN45BQbhFMDtKlm+aAM3QtFJdh9nx1sRCKguGwcCSgGqIxlE9n1TRiQbsszYt59xIKio4jJc7NDFiKDeEfvFbosgW03RsTbu2+ErnbxbEZrvRGqaKYA+uaIMxcAZ/kIZWmbsz452Quz8WIXmsZm3WWyORQdtwvz9gtWZjzo9Yz1GKnA6KdGRI83SkMWu5CrCeAuTS9t0q/gmK4limXMzUKEUho6gUyDdnEn6Ej8DIcGjD1sH3GRk/nkyaRYo7YvO3leODzBq/7qMRIRXLem9ohuxlUDZmqrEQJcDpyOMObKgkD9M6IyQrzSdH+K94gl6mzHwvMOdxxXicC5j35MXbiq++S22TnmMGCqtPgZdWd9xjjfDySUvwqX0o7UesDJhcylOfx6t5FbMnWR1y/NurTSBTxzuvB2GrhsEMg4icAMcGB5r03O2zCyGOFYFwuwWCGzAqnE6erymc6Qm6MscFtw==
  template:
    metadata:
      name: camunda-platform-keycloak
      namespace: camunda
    type: Opaque
