---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-credentials
  namespace: camunda
spec:
  encryptedData:
    password: AgApqIYYCutzgk97niwH+dU0aa6V1ZAvKJa4ZCzE/XOROI3eHSot0tgO4JHgp7gQy57TA8gY1y+l8RdaC+3DaazZ3cra7JhF6jFK7sfYNKRM9mIBja2Vq0gv9lt+oy4t2jU5cIRKYtAxVdU76V15cPOVrSI+7THfaP3RZz1TcyALRHCA4pcMLDb+jxGYe27dd2EQroqs6P3FXspyaRoshOm2X97PZhs5YMTc8THdFasi52L0m4pP+CFyVcCug3OBq2IQtkSz89ObsTr0o4qCCDhZD1ksuQbPC+xQWQtCVeR9+ZHj8Z1a94a/hKhoS9KSqs4Z1Yv1mAwi2pR3oPGGtY87UJGj9BDhTNgVVWlp7Ju4PXSH5eL2eCMhqkJZ0iRhmdWb4ft+SMZBO58ZVNFiMVq9b3DkLvAKvYeoXfijQCcQ86/lHjQpFJBz9D1yojxneLhuAT/yTZ+xF9jC+R54QDrQyzWAai2gKP67a5csqTWFIRGAN3GpSgrhHN2Wu0bPITVmw/c3XsPh6N3eMttggeis9IWgQWfiwmTY/HAvFACqAv6I6aLpqDicEbQq+SPVE6HbRY33/KASCiwFt3QszzxreGqTAMFrVc4KBHOq8w1q/UAOBhYSFIx3wKZ98e5aCVtZX0flz3/Xus1puFbECPP6cSQ6KCk78oBDnl+5bwIvyLprYmOo6X3yv5jSZaXsJW5qOtVWsutwTcHkKQ==
    postgres-password: AgBsteA7XFXsWid1KsuP07wwow9cK6q4tXVAgLdIwe7JiyoVpV8MNzR6ByIVRhZE8JCMqcAg7lMLFTqtKABqMCd7CV0wYh97+AnbnKnZMof5T0EEkyyJBI267dtd8HztOt7DvL2cTX5fX0g/AmIglc+CbYRlN+kzkEQvcn6DTukbiSDyRXR204Uxx4nzq1pC1Qc1p4ynGtw07lUX67DnyzbgLqexYiDLqg1wCZw4kNnDvNCmCQIfmD921hgBjsuVrif2iuvdHk2beaAAASAuY/l6zLDLV7XKvIQSSqUe5L+1Phh39LglzjpZME1zaBk2ufOyESvnlZIosi4lU+nCRTdDgqQauOBpBJC6Ncu339BfR2qWj1b3bM7IIzsiRhnfcwOT6aDEzkWMuQQkWWrq3R0ZbwYTK6x75SV904Yhf9coR80EqzkVchc9gA1Z6zPFcZszXMX9ztoUCQGkl5/aXDUMVEXi9RCtyAcG9NurBjuFhoovJBVV8KKwKGs4peYk7pUknpRNsvlorfsmZb22RTfiNsuXMbgSekrOCSRaeKKUdSXcNjTsCA8oB8zXZpUqLWLBdMyWAe+JvLpkTLBEVMqAy4RR5MoAXjWkzxvkPFXJUL+rDk8gP1Q6oVDZOPyIHZJfW7cu/YowAB7K32tyfrRS55NgqgZNtEFSvf/m/TdARUzluWvNhQEfI8riMY2FBngaEHbRqcm23o2p9w==
  template:
    metadata:
      name: postgresql-credentials
      namespace: camunda
    type: Opaque
