---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-db-secret
  namespace: keycloak
spec:
  encryptedData:
    password: AgCUotL3uZRC2Zw+2HWYVFv8I2+5rmHRL0H5I4rhmP8S9H/5T20vf37I+1DjeXZoTw29zYQ+NTcdfasfi1x04ltJ1H1BiS83Y4aSvL2qa+DEB/sQP/uTr79zmu4Aq1/91TNGEwKsH71uKd9cbzoAibPZYSfmkiB1jcfjpvDRtDOZPbIzJbllqG3qv+l7oL0EsytHmFFJGeLfh+jrOVryiY2gejiLQBR1vwLEgyQSax/GdQmDHxPILZJzktFlnfmdmmYwmiXeP1SnZGf090NnF/p1tvkPW1pmQ4SFyVyTOv3jwpX32M1aIqjPXLDnRTIVzNO5Uy5u59+Ar7Lb2kjddQAQdii3CmeoEdqfQvoZUe92V/OWPkTEIKlFYEBY1l1zKl/U8IC5sbeeh7xLXOfMQhlCmvl0NCvnEArmX5O3E+RO0rfm7BHmsk1OturVF0MpS0QBfcfzoYxPEO6tI+rRLRVI3BwLUyWRetRJHrzY6c2UiLqdZ0KdoZlSXPXaY73PwiCYOv0i6IpzQIHzxz8kEwqxOH2pDL7XRY6lwiVy6/Zigt6TRPkoZfaP0HWqyH+EFIPepfh+teVPC34zv2c+8hQwJEva+bogVs0MSaHwwUwsK4h8BEpOO8eeNo+Bxp0tAq9EFFVGpWS8tUJjZhMR82peg2e1wng0tYSNaiaZ9/sLYSnY5p/anckVrB416F2HoSNmRgen6qHLNnRXPZ2xhSlvhV5Mb6zP4lVAr2tH693tdOlFj6JFH4DUdpUm5w==
    username: AgBCSrW/EyoafEN8ya5SrpTV+pPdM2TcVc4hW9+k4Xhdqf9CPBjBa/v6fqEuJI+EhzqtW8q0J/zJFWrbYE8WYUxAuoDNePonpRwJgorwh80hbwbZ8bA1A9nqMsa0CTX/N7VSXBwD0DBTZKAgC/7ghX0Flt550SG+1IoXl9rgF3xqgq0F/uvW04m+Y4lifV1UOBr7p5oCuRWI7Krt4/Z1Mm1D1eK/koVWM2a37JopRBPeoxemLq/mRgSmK1JeKD7gJZtowzwZ72ydR9Uw+3iDuTG9WEDH0RtDL0+jFeOeYUwNZkeMeYZJuY4amdZ63JFygVRU/qQ39zdPgBkP7sb7cNPPUcVCfF2l7ACtOawvIFUWyjFHu70zHGE9T4KOmEP6WbwjGdxAss10Keo6SpTVM0b7ddx5o3Ej18BMGTrajIKCsPnleK38nbPiYEOeOWSd5VFghdNRF5hbV9M9sMVz7XQS7YWbPSgfzrCMBXkP3Bl7Z3Qg7hEkc6QodQRQJ7tSaV/HM7ecMUWjHs60xQCXkHtF3cFWuG5I2omQw2AlswmzrdeAqH4GJNPT6SiFo6zFawJ79lEuU5UPhEPIPe6H9DXZvDRF7poblWFKvBwTzBD8KPzSuNcjAuggvC2uZ+/nuJxkPbkZcO16ScC7eMkrgsN8pRVJiYHhmo9j5LFqRnJ7mwY+GHsXOeBM7OGPzgTCpKns6uShmevaYA==
  template:
    metadata:
      name: keycloak-db-secret
      namespace: keycloak
    type: Opaque
