---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgDJGQ9xMgAgIf0S7K1eTe9ukln6X2mqoSgYPcU0Wie46b0kPUI8y2dByIPtRY/LO1PWUIPto2JPCMkjlxws7Tx2+8MVpRcBaiGhhLY6X7UmvuSQafrCsDFLVy7mikl8kj4YWXSScK2bvcVJOE3jRMY24oJVW/hwTtBxBkluUAFmM+hHDm4tQwad8wY3G9JtIUrPMp6I9g+/cIoF87U8nsbrBavUUznpXSuPGfZlUk5ImqxCIq6QlhJ1eK1IcICHv+39RTEUvFB526D7RKhSU8rT5WN2oVVQ82N9aFP0NoFYu/w4zyFa/eAxk/yaBvEFgYsGk8SbS7A5s/JVeq88EIGh/2BoEQrPoarFyhU6DcBMU9ghWxniPlsoVMe4E8b7MteMJdF2wTyq7zize5S0cqXKH6ZmeLeh5HZIYqoUkQZ0qk6XSGDAJBomYH7Is3TJkhLFjLppPpVIAlJu5Bu/M/xi+GJHNkLMSSFGyvWO5AVSXGY74Cbaho0E0MCR/YXSzNmF9SIKdZ/btnvTmORxm+oUSJb4M19VHrsLRCAOSb6cilTKhHgQBSFyFxFnySiYvVRF2SZJQGOZxjYamFTGiKq23nntibjvAKsZdGvJI4Rxz+M06a+W5k34Rqh44rU9Sx8+i6cyirTY9o5JAeHsVuQrnB3AJbxXxYv3drZMQlgxIhJnkwlKQkLluIXxH/XMUS5V3GQucOZoNw4xWXuVK3ewwV4UM7mO8MNx4KKYAhlHvscdEd1vi7/RAaVsrA==
    admin-user: AgCwr6a4+xF+CvaLki0qF4ZNZpGOPetJ1midEWtavJahL90sz28nwTn3ul6w0pGKGxQ1ePh6lubMGX6DGc/hvV1XHNaOhmXEN5AzQxW53x61y7CQLGzpedtZNhSEvV2/6ZfMeYBaAjz/vYwFrt+dvvSaVpjT+3LV6rLTQKf4/tT8YehfQsQS56tW5i3WMoUphfHZPqnLcTEHResBePMJrGePHQabNuHR60emLttnkkYPoOrOc2c0iIAkRUm8rF/XrFb9GdhOXIuvB8NBla8WbzIXxmzUqxD33RRH7uSYGSI8BPwl5Ok8hCqnSAWd36jFdyBpELN+qmeiOYlV7l1x2TwZ4VGNtJXOjY2L+kV0MuerLNRg4ZxQueCz5jYSpkqiGapjZIlG2gkvg1Zn4nKWh367Qzg6nQ1Itk0hrM0OdHx7Q8/CGiOlrWeiObQOmZnAYGdt5MCHNyoaFDQgVIuBYFvawg+BGswIMuFMfM5X48IPUnl5X+GLZaWAi2JLJ/qxr66QsiKPBfZzBpRwQIfL/igfv49dzwWJUo/n1BXlIjOsJBPF13fVqnPb2OPpJtfBj1mD65E78auiDCHIo9Q013AZWxavkTYhToXvAgM9rr1XsxwkhFc6tETG4Hj6E4S7Y07POoHk+SFeFCEa398gWbDmTuY74nA+lNwpJg6TQ7yt3y3G9TQwQUiwTcpHACf4UmCPG3n/bQ==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
