apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: camunda-platform
  repo: https://helm.camunda.io
  releaseName: camunda
  version: 8.2.x
  valuesFile: values.yaml
  includeCRDs: true

configMapGenerator:
- name: common-config
  literals:
    - ENVIRONMENT=base