# production/k8s/postgres/adoptable-secret-mirror.yaml
apiVersion: v1
kind: Secret
metadata:
  # O nome que o PGO espera
  name: camunda-pg-cluster-pguser-keycloak
  namespace: keycloak # O mesmo namespace do PostgresCluster
  # As labels que o PGO espera
  labels:
    postgres-operator.crunchydata.com/cluster: camunda-pg-cluster
    postgres-operator.crunchydata.com/pguser: keycloak
  # A anotação que instrui o Reflector a agir!
  annotations:
    # Formato: <namespace-fonte>/<nome-do-segredo-fonte>
    reflector.v1.k8s.emberstack.com/reflects: "keycloak/keycloak-password-source"
type: Opaque
# Note que não há campo 'data' ou 'stringData'.
# O Reflector irá preencher e gerenciar esses campos.