# Path: production/charts/postgres/cluster-cr.yaml
# Este é um Recurso Customizado (CR) que o operador PGO irá usar para criar o cluster.
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: camunda-pg-cluster
  annotations:
    # Habilita a funcionalidade de criação de usuários a partir de segredos pré-existentes.
    postgres-operator.crunchydata.com/users-from-secret: "true"
spec:
  postgresVersion: 15 
  databases:
  - name: keycloak  # Cria o banco de dados 'keycloak' necessário para o Keycloak
  instances:
    - name: instance1
      replicas: 1 # Apenas uma instância para ambiente de nó único
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 20Gi
        storageClassName: longhorn
      # Permite que o pod rode no nó de controle (master)
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
  backups:
    pgbackrest:
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessModes:
              - "ReadWriteOnce"
              resources:
                requests:
                  storage: 20Gi
              storageClassName: longhorn
  proxy:
    pgBouncer:
      replicas: 1
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
