# production/k8s/postgres/external-secret-keycloak.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-db-password-sync
  namespace: keycloak
spec:
  # Aponta para a loja que criamos no Passo 2
  secretStoreRef:
    name: kubernetes-backend
    kind: ClusterSecretStore

  # Define o segredo alvo que será atualizado
  target:
    name: camunda-pg-cluster-pguser-keycloak
    # ESTA É A POLÍTICA MÁGICA:
    # Apenas mescla os dados, não assume propriedade.
    creationPolicy: Merge

  # Define o segredo fonte e quais chaves buscar
  data:
  - secretKey: password # A chave no segredo alvo a ser escrita
    remoteRef:
      # O segredo fonte gerenciado pelo Sealed Secrets
      key: keycloak/keycloak-password-source
      # A chave dentro do segredo fonte a ser lida
      property: password