apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  annotations:
    # Wave -10: Instalação base de certificados, uma das primeiras dependências.
    argocd.argoproj.io/sync-wave: "-10"
  namespace: argocd
spec:
  project: camunda-platform
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    # Ajuste a versão se necessário
    targetRevision: v1.15.3
    helm:
      releaseName: cert-manager
      valuesObject:
        installCRDs: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
