# Path: production/argocd/apps/longhorn.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: camunda-platform
  source:
    repoURL: "https://charts.longhorn.io"
    chart: longhorn
    targetRevision: "1.9.1"
    helm:
      valuesObject:
        enablePreUpgradeChecker: false
        manager:
          tolerations:
            - key: "node-role.kubernetes.io/control-plane"
              operator: "Exists"
              effect: "NoSchedule"
            - key: "node-role.kubernetes.io/master"
              operator: "Exists"
              effect: "NoSchedule"
        settings:
          createDefaultDiskLabeledNodes: true
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
