apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: camunda-platform
  destination:
    namespace: longhorn-system
    server: https://kubernetes.default.svc
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    # Ajuste a versão se necessário
    targetRevision: 1.5.3
    helm:
      releaseName: longhorn
      valuesObject:
        defaultSettings:
          # Ajuste se quiser um caminho de dados diferente
          defaultDataPath: /var/lib/longhorn
          # Réplicas padrão por volume (para single-node pode ser 1)
          defaultReplicaCount: 1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

