# Path: production/argocd/apps/longhorn.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    # Wave 0: Garante que o armazenamento seja instalado APÓS o RBAC (wave -5)
    # e ANTES de aplicações que o utilizam (ex: Camunda, wave 10).
    argocd.argoproj.io/sync-wave: "0"
  name: longhorn
  namespace: argocd
spec:
  project: camunda-platform
  destination:
    namespace: longhorn-system
    server: https://kubernetes.default.svc
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: 1.6.2 # Mantendo a versão desejada
    helm:
      releaseName: longhorn
      valuesObject:
        # Instrui o chart a NÃO criar um ServiceAccount, pois ele já é
        # gerenciado pela aplicação 'longhorn-rbac'.
        serviceAccount:
          create: false
        defaultSettings:
          defaultDataPath: /var/lib/longhorn
          defaultReplicaCount: 1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true