apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../k8s/longhorn-prereqs/service-account.yaml

helmCharts:
- name: longhorn
  repo: https://charts.longhorn.io
  version: 1.9.1
  releaseName: longhorn
  namespace: longhorn-system
  valuesInline:
    enablePreUpgradeChecker: false
    serviceAccount:
      create: false
    defaultSettings:
      defaultDataPath: /var/lib/longhorn
      defaultReplicaCount: 1
