# Path: production/argocd/apps/dependencies/8-keycloak-instance.yaml
# Este arquivo cria uma aplicação dedicada para a instância do Keycloak.
# A app-of-apps irá gerenciar ESTA aplicação, e não o CR diretamente.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-instance
  namespace: argocd
  annotations:
    # Wave 8: Cria a instância DEPOIS que a aplicação do operator (Wave 7) estiver saudável.
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: camunda-platform
  source:
    repoURL: git@github.com:Unicoon-Protecao-Veicular/SGP.git # Substitua pelo seu repo
    # ATENÇÃO: O path aponta para o diretório onde o Custom Resource está,
    # que deve ser DIFERENTE do path da sua 'app-of-apps'.
    path: production/helm-values/keycloak
    targetRevision: feat/new-architecture
  destination:
    server: https://kubernetes.default.svc
    namespace: camunda
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
