# Path: production/argocd/apps/dependencies/7-keycloak.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  annotations:
    # Wave 7: Instala o Keycloak DEPOIS que o cluster Postgres está pronto.
    argocd.argoproj.io/sync-wave: "7"
spec:
  project: camunda-platform
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: keycloak
    # CORREÇÃO: Usando uma versão de chart válida e recente.
    # O chart 19.2.5 instala a aplicação Keycloak 24.0.4.
    targetRevision: 19.2.5
    helm:
      # Aponta para o arquivo de values customizado no seu repositório Git
      # ATENÇÃO: Verifique se este caminho está correto em relação à raiz do seu repositório.
      valueFiles:
        - https://raw.githubusercontent.com/Unicoon-Protecao-Veicular/SGP/main/production/helm-values/keycloak/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: camunda # Instala o Keycloak no namespace principal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

